const continentMapping = {
    // North America
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "North America",
    "Guatemala": "North America",
    "Cuba": "North America",
    "Haiti": "North America",
    "Dominican Republic": "North America",
    "Honduras": "North America",
    "Nicaragua": "North America",
    "El Salvador": "North America",
    "Costa Rica": "North America",
    "Panama": "North America",
    "Jamaica": "North America",
    "Trinidad and Tobago": "North America",
    "Bahamas": "North America",

    // South America
    "Brazil": "South America",
    "Argentina": "South America",
    "Colombia": "South America",
    "Chile": "South America",
    "Peru": "South America",
    "Venezuela": "South America",
    "Ecuador": "South America",
    "Bolivia": "South America",
    "Paraguay": "South America",
    "Uruguay": "South America",
    "Guyana": "South America",
    "Suriname": "South America",

    // Europe
    "United Kingdom": "Europe",
    "Germany": "Europe",
    "France": "Europe",
    "Netherlands": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Russia": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Poland": "Europe",
    "Norway": "Europe",
    "Finland": "Europe",
    "Denmark": "Europe",
    "Ireland": "Europe",
    "Belgium": "Europe",
    "Portugal": "Europe",
    "Greece": "Europe",
    "Austria": "Europe",
    "Czech Republic": "Europe",
    "Hungary": "Europe",
    "Romania": "Europe",
    "Bulgaria": "Europe",
    "Slovakia": "Europe",
    "Croatia": "Europe",
    "Slovenia": "Europe",
    "Serbia": "Europe",
    "Lithuania": "Europe",
    "Latvia": "Europe",
    "Estonia": "Europe",
    "Luxembourg": "Europe",
    "Iceland": "Europe",
    "Malta": "Europe",
    "Monaco": "Europe",
    "Liechtenstein": "Europe",
    "Andorra": "Europe",
    "San Marino": "Europe",
    "Bosnia and Herzegovina": "Europe",
    "Macedonia": "Europe",
    "Montenegro": "Europe",
    "Albania": "Europe",

    // Asia
    "China": "Asia",
    "Japan": "Asia",
    "India": "Asia",
    "South Korea": "Asia",
    "Indonesia": "Asia",
    "Turkey": "Asia",
    "Saudi Arabia": "Asia",
    "United Arab Emirates": "Asia",
    "Thailand": "Asia",
    "Malaysia": "Asia",
    "Singapore": "Asia",
    "Vietnam": "Asia",
    "Philippines": "Asia",
    "Pakistan": "Asia",
    "Bangladesh": "Asia",
    "Sri Lanka": "Asia",
    "Kazakhstan": "Asia",
    "Israel": "Asia",
    "Lebanon": "Asia",
    "Jordan": "Asia",
    "Iraq": "Asia",
    "Qatar": "Asia",
    "Kuwait": "Asia",
    "Oman": "Asia",
    "Uzbekistan": "Asia",
    "Nepal": "Asia",
    "Cambodia": "Asia",
    "Laos": "Asia",
    "Bahrain": "Asia",
    "Myanmar": "Asia",
    "Afghanistan": "Asia",
    "Armenia": "Asia",
    "Yemen": "Asia",
    "Syria": "Asia",
    "Georgia": "Asia",
    "Azerbaijan": "Asia",
    "Maldives": "Asia",
    "Mongolia": "Asia",

    // Africa
    "South Africa": "Africa",
    "Nigeria": "Africa",
    "Egypt": "Africa",
    "Kenya": "Africa",
    "Ethiopia": "Africa",
    "Ghana": "Africa",
    "Morocco": "Africa",
    "Algeria": "Africa",
    "Tanzania": "Africa",
    "Uganda": "Africa",
    "Angola": "Africa",
    "Cameroon": "Africa",
    "Ivory Coast": "Africa",
    "Senegal": "Africa",
    "Zimbabwe": "Africa",
    "Sudan": "Africa",
    "Rwanda": "Africa",
    "Libya": "Africa",
    "Mozambique": "Africa",
    "Botswana": "Africa",
    "Namibia": "Africa",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Zambia": "Africa",
    "Gabon": "Africa",
    "Mali": "Africa",
    "Burkina Faso": "Africa",
    "Chad": "Africa",
    "Niger": "Africa",
    "Benin": "Africa",
    "Tunisia": "Africa",
    "Somalia": "Africa",
    "Guinea": "Africa",
    "Sierra Leone": "Africa",
    "Mauritania": "Africa",
    "Liberia": "Africa",
    "Djibouti": "Africa",
    "Equatorial Guinea": "Africa",
    "Eswatini": "Afric
